### ISSUE TITLE
폴더명

### ISSUE THREAD

**Issue by lee-sj** [JungWooJin97/Likesession#1]
폴더명은 영어로 하는것을 권장합니다. 
그리고 폴더에 띄어쓰기는 쓰지않는것을 권장합니다. 
띄어쓰기를 쓰고자 할때는 아래와 같은 예시 중 한가지를 활용해보세요

ex) jung woo jin 을 쓰고자 할때는 아래의 방법 중 한가지로 작성해보세요
jung_woo_jin
JungWooJin
Jung_Woo_Jin
Jung_woo_jin

구글에 '파일명 공백' 이나 '폴더명 띄어쓰기'등으로 검색해보는것을 추천합니다. 
@JungWooJin97

**Comment by JungWooJin97** [comment]
넵 감사합니다.
